name: "Test screenshot taking"
on:
  workflow_dispatch:
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Python version from .python-version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync
      - name: Prepare tweet
        run: |
          pipenv run python prepare_tweet.py
      - name: Set up git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes if any
        run: |
          git checkout -B screenshot
          git add -f graph.png
          git diff --staged --quiet || git commit -m "Generate graph.png from GitHub Action ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          git push -fu origin screenshot
